# Generated by Django 5.0.4 on 2024-05-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Redmi', 'Redmi'), ('Samsung', 'Samsung'), ('Apple', 'Apple'), ('Realme', 'Realme')], max_length=100),
        ),
    ]
