# Generated by Django 5.0.4 on 2024-05-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_category_description_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Redmi', 'Redmi'), ('Samsung', 'Samsung'), ('Apple', 'Apple'), ('Realme', 'Realme')], max_length=100, unique=True),
        ),
    ]
